
--1. What is the total revenue generated by male vs female customers?

SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

--2. which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND
      purchase_amount >=(
SELECT AVG(purchase_amount)
FROM customer
);

--3. which are the top 5 products with the highest average review ratings?

SELECT item_purchased, AVG(review_rating) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY 2 DESC LIMIT 5;

--4. compare the average purchase amounts between standard and express shippings?

SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type
ORDER BY 2 DESC ;

--5. Do subscribed customers spend more? Compare avg spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status,
       COUNT(customer_id) AS count_customers,
       AVG(purchase_amount) AS avg_amount,
	   SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

--6. Which 5 products have the highest percentage of purchases with discount_applied?

SELECT item_purchased, 
       ROUND(100* SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY 2 DESC 
LIMIT 5;

/*7. Segment customers into new, Returning and Loyal based on their total
     number of previous purchases and show the count of each segment?*/

WITH customer_type AS (
SELECT customer_id, previous_purchases,
       CASE
	   WHEN previous_purchases = 1 THEN 'New'
	   WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	   ELSE 'Loyal'
	   END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS Number_of_customer
FROM customer_type
GROUP BY customer_segment;

--8. What are the top 3 most purchased products within each category?

WITH item_count AS (
SELECT category, item_purchased,
       COUNT(customer_id) AS total_orders,
	   ROW_NUMBER() OVER(PARTITION BY category ORDER BY 3 DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT * FROM item_count
WHERE item_rank <= 3;

--9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--10. What is the revenue contribution of each age group?

SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY 2 DESC;

--11. Which 10 locations generate the highest total revenue?

SELECT location,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 10;

--12. Which payment method is used most frequently?

SELECT payment_method,
       COUNT(*) AS total_orders
FROM customer
GROUP BY payment_method
ORDER BY total_orders DESC;

--13. Which season generates the highest revenue?

SELECT season,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY season
ORDER BY total_revenue DESC;

--14. Which category performs best in each season based on total revenue?

WITH seasonal_sales AS (
SELECT season,
       category,
       SUM(purchase_amount) AS revenue,
       ROW_NUMBER() OVER(PARTITION BY season ORDER BY SUM(purchase_amount) DESC) AS rank_no
FROM customer
GROUP BY season, category
)
SELECT season, category, revenue
FROM seasonal_sales
WHERE rank_no = 1;

--15. Rank the top 10 highest-spending customers based on total purchase amount

SELECT customer_id,
       SUM(purchase_amount) AS total_spent
FROM customer
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 10;
